/* Gastos · Crédito: sección aparte con gráficos de torta, fechas y botón de pago. Se carga después de etapa25.js. */
const proxDia=d=>{const h=hoyS(),b=cobroFecha({dia:d},h);return b>=h?b:cobroFecha({dia:d},iso(new Date(+h.slice(0,4),+h.slice(5,7),1)))};
const enDias=f=>Math.round((dt(f)-dt(hoyS()))/864e5),cuando=n=>n==0?'hoy':n==1?'mañana':`en ${n} días`,d31=v=>{v=parseInt(v);return v>=1&&v<=31?v:null};
const torta=P=>{const T=P.reduce((a,x)=>a+x[1],0)||1,C=2*Math.PI*40;let o=0;return `<svg viewBox="0 0 160 160" width="170" height="170" role="img" aria-label="Gráfico de torta">${P.map(x=>{const l=x[1]/T*C,s=`<circle cx="80" cy="80" r="40" fill="none" stroke="${x[2]}" stroke-width="80" stroke-dasharray="${l.toFixed(1)} ${C.toFixed(1)}" stroke-dashoffset="${(-o).toFixed(1)}" transform="rotate(-90 80 80)"/>`;o+=l;return s}).join('')}</svg>`};
const leyenda=P=>`<div style="width:100%;display:flex;flex-direction:column;gap:8px">${P.map(x=>`<div class="l"><span><i style="display:inline-block;width:10px;height:10px;border-radius:5px;background:${x[2]};margin-right:8px"></i>${esc(x[0])}</span><span>${fm(x[1])}</span></div>`).join('')}</div>`;
const PAL=['#5B8CFF','#4FD1A5','#F2B54B','#FF7A6B','#B58CFF','#98A2AE'];
function vCredito(){const cs=S.cuentas.filter(c=>c.tipo=='credito');
 return `<button class="lnk" style="align-self:flex-start" onclick="S.sub=null;draw()">◀ Mi plata</button><h1>Crédito</h1>`+(cs.map(c=>{const d=saldoC(c),cu=c.cupo||0,p=cu?d/cu:0,col=p>=1?'#FF7A6B':p>=.8?'#F2B54B':'#5B8CFF',mes=hoyS().slice(0,7),g={};
  S.movs.filter(x=>x.cuenta_id==c.id&&x.fecha.slice(0,7)==mes).forEach(x=>{const n=S.sobres.find(b=>b.id==x.sobre_id)?.nombre||'Pagos fijos';g[n]=(g[n]||0)+x.monto});
  const L=Object.entries(g).sort((a,b)=>b[1]-a[1]).slice(0,6).map((x,i)=>[x[0],x[1],PAL[i]]),fe=[];
  if(c.dia_cierre){const f=proxDia(c.dia_cierre);fe.push(`Cierra el ${dm(f)} (${cuando(enDias(f))})`)}if(c.dia_venc){const f=proxDia(c.dia_venc);fe.push(`Vence el ${dm(f)} (${cuando(enDias(f))})`)}
  return `<div class="card" style="align-items:center"><div class="l" style="width:100%"><b>${esc(c.nombre)}</b><small>Cupo ${cu?fm(cu):'sin definir'}</small></div>
  ${cu?`${torta([['Usado',Math.min(d,cu),col],['Disponible',Math.max(0,cu-d),'#3A424C']])}<b class="big3">${Math.round(p*100)}% del cupo usado</b>${leyenda([['Debes',d,col],['Cupo disponible',Math.max(0,cu-d),'#3A424C']])}`:`<b class="big3">Debes ${fm(d)}</b><small>Agrega el cupo en Editar para ver el gráfico.</small>`}
  <small>${fe.join(' · ')||'Agrega el día de cierre y de vencimiento en Editar.'}</small>
  <div class="r2" style="width:100%"><button class="btn" onclick="pagarCredito('${c.id}')">Pagar crédito</button><button class="btn2" onclick="nuevaCuenta('${c.id}')">Editar</button></div></div>
  <div class="card" style="align-items:center"><b style="align-self:flex-start">Qué compraste con ${esc(c.nombre)} este mes</b>${L.length?torta(L)+leyenda(L):'<small>Aún no hay compras con este crédito este mes.</small>'}</div>`}).join('')||'<p>No tienes una cuenta de crédito. Créala en Mi plata con el tipo Crédito.</p>')}
function pagarCredito(id){traspaso();if(!$('#td'))return;$('#th').value=id;const o=S.cuentas.find(x=>x.id==cuentaDef()&&x.tipo!='credito')||S.cuentas.find(x=>x.tipo=='banco');if(o)$('#td').value=o.id;$('#tm').value=saldoC(S.cuentas.find(c=>c.id==id))||''}
vPlata=function(){if(S.sub=='credito')return vCredito();const C=S.cuentas;
 if(!C.length)return `<h1>Mi plata</h1><p>Aquí anotas dónde tienes tu plata: efectivo, bancos, ahorro y crédito. Así la app sabe de dónde sale cada gasto y cuánto tienes de verdad.</p><button class="btn" onclick="semilla()">Crear mis cuentas</button><button class="btn2" onclick="nuevaCuenta()">Crear una cuenta a mano</button>`;
 const p=plata(),sa=semAhorro(),N=id=>esc(S.cuentas.find(c=>c.id==id)?.nombre||'Cuenta quitada'),
 card=c=>`<div class="card"><div class="l"><b>${esc(c.nombre)}</b><small>${TIPOS[c.tipo]}</small></div><b class="big3">${fm(saldoC(c))}</b><div class="r2"><button class="btn2" onclick="corrige('${c.id}')">Corregir saldo</button><button class="btn2" onclick="nuevaCuenta('${c.id}')">Editar</button></div></div>`,
 sec=(t,l)=>l.length?`<h4>${t}</h4>`+l.map(card).join(''):'',
 cr=C.filter(c=>c.tipo=='credito').map(c=>{const d=saldoC(c),cu=c.cupo||0,pc=cu?d/cu:0;return `<button class="card" style="text-align:left;border:0;border-left:4px solid var(--r);color:inherit;font:inherit;cursor:pointer" onclick="S.sub='credito';draw()"><div class="l"><b>${esc(c.nombre)}</b><small>Crédito · toca para ver el detalle</small></div><span>Debes <b class="big3">${fm(d)}</b></span>${cu?`<div class="t"><i style="width:${Math.min(100,pc*100)}%;background:${pc>=.8?'var(--y)':'var(--a)'}"></i></div><small>Cupo disponible ${fm(cu-d)} de ${fm(cu)}</small>`:''}</button>`}).join('');
 return `<h1>Mi plata</h1><div class="hero"><span>Plata libre de verdad</span><b>${fm(p.libre)}</b><span>Para gastar ${fm(p.gastar)} − apartado en fijos ${fm(p.apart)} − deuda ${fm(p.deuda)}</span></div>
 ${sec('Para gastar',C.filter(c=>['efectivo','banco'].includes(c.tipo)))}${sec('Ahorro',C.filter(c=>c.tipo=='ahorro'))}${p.ahorro>0&&sa?`<small>Tu ahorro cubre ${sa.toFixed(1)} semanas de gasto, según el promedio de las últimas 4 semanas.</small>`:''}${cr?'<h4>Crédito · lo que debes</h4>'+cr:''}
 <div class="r2"><button class="btn" onclick="traspaso()">Traspaso</button><button class="btn2" onclick="nuevaCuenta()">+ Cuenta</button></div>
 ${S.tras.length?'<h4>Últimos traspasos</h4>'+S.tras.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha)).slice(0,8).map(t=>`<div class="mv"><div><b>${N(t.desde)} → ${N(t.hacia)}</b><small>${dm(t.fecha)}${t.nota?' · '+esc(t.nota):''}</small></div><b>${fm(t.monto)}</b><button class="x" aria-label="Borrar traspaso" onclick="delTras('${t.id}')">✕</button></div>`).join(''):''}`};
const _nc=nuevaCuenta;nuevaCuenta=function(id){_nc(id);const c=S.cuentas.find(x=>x.id==id)||{};$('#cc').insertAdjacentHTML('afterend',`<input id="cci" inputmode="numeric" placeholder="Día de cierre del mes (solo crédito)" value="${c.dia_cierre||''}" aria-label="Día de cierre"><input id="cve" inputmode="numeric" placeholder="Día de vencimiento del pago (solo crédito)" value="${c.dia_venc||''}" aria-label="Día de vencimiento">`)};
guardaCuenta=async function(id){const o={nombre:$('#cn').value.trim(),tipo:$('#ct').value,cupo:parseM($('#cc').value)||null,dia_cierre:d31($('#cci').value),dia_venc:d31($('#cve').value)};if(!o.nombre)return toast('Falta el nombre');
 const r=id?await SB.from('cuentas').update(o).eq('id',id):await SB.from('cuentas').insert({...o,orden:S.cuentas.length});if(r.error)return toast(r.error.message);$('#dlg').close();cargar()};
const _d2=draw;draw=function(){if(S.v!='plata')S.sub=null;_d2()};
const _v3=vInicio;vInicio=function(){let h=_v3();const w=(S.cuentas||[]).filter(c=>c.tipo=='credito'&&c.dia_venc&&saldoC(c)>0).map(c=>[c,enDias(proxDia(c.dia_venc))]).filter(x=>x[1]<=5);
 if(w.length)h=h.replace('</h1></div>',`</h1></div><div class="warn" style="grid-column:1/-1">${w.map(x=>`El pago de ${esc(x[0].nombre)} vence ${cuando(x[1])}. Debes ${fm(saldoC(x[0]))}.`).join('<br>')}<br><button class="btn" style="margin-top:10px" onclick="S.sub='credito';ir('plata')">Ver crédito</button></div>`);return h};
const _ay2=ayuda;ayuda=function(){if(!(S.v=='plata'&&S.sub=='credito'))return _ay2();const d=$('#dlg');d.innerHTML=`<h3>Crédito</h3><p>El primer gráfico muestra cuánto de tu cupo ya usaste. El segundo, en qué gastaste con esta tarjeta este mes. "Pagar crédito" arma un traspaso desde tu banco hacia la tarjeta, que baja tu deuda y no cuenta como gasto. Para ver las fechas de cierre y vencimiento, agrégalas en Editar.</p><button class="btn" onclick="this.closest('dialog').close()">Entendido</button>`;d.onclose=null;d.showModal()};
/* ---- total que tengo, sin contar el crédito ---- */
const _vp=vPlata;vPlata=function(){const h=_vp();if(S.sub=='credito'||!S.cuentas.length)return h;
 const C=S.cuentas.filter(c=>c.tipo!='credito'),A=C.map((c,i)=>[c.nombre,saldoC(c),PAL[i%6]]),T=A.reduce((a,x)=>a+x[1],0);
 return h.replace('<h1>Mi plata</h1>',`<h1>Mi plata</h1><div class="card" style="align-items:center"><div class="l" style="width:100%"><span>Tengo en total</span><small>sin contar el crédito</small></div><b class="big3" style="font-size:40px;align-self:flex-start">${fm(T)}</b>${A.some(x=>x[1]>0)?torta(A.filter(x=>x[1]>0))+leyenda(A):''}<small style="align-self:flex-start">Suma efectivo, bancos y ahorro. No incluye lo que debes ni el cupo del crédito.</small></div>`)};
const _v4=vInicio;vInicio=function(){const h=_v4();if(!(S.cuentas||[]).length)return h;const T=S.cuentas.filter(c=>c.tipo!='credito').reduce((a,c)=>a+saldoC(c),0);return h.replace('<small>Para gastar',`<small>Tengo en total ${fm(T)} (sin crédito) · Para gastar`)};
if(S.user)cargar();
