/* Gastos · Etapa 2.5: Mi plata (cuentas, saldos y traspasos). Se carga después de etapa2.js. */
const st2=document.createElement('style');st2.textContent=`#app{padding-top:0}main{padding:22px 0 48px}#toast{bottom:24px}
nav{position:sticky;top:0;bottom:auto;left:auto;right:auto;max-width:none;width:auto;margin:0 -18px;padding:calc(env(safe-area-inset-top) + 8px) 18px 8px;border-top:0;border-bottom:1px solid var(--l);justify-content:flex-start;gap:8px;z-index:5}
nav .brand{display:none}nav .tabs{display:flex;gap:2px;flex:1;min-width:0;overflow-x:auto}
nav .tabs button{flex:none;min-width:0;padding:0 8px;font-size:12px;min-height:44px;color:var(--m);background:none;border-radius:0;border-bottom:2px solid transparent}
nav .tabs button.on{color:var(--a);font-weight:700;border-bottom-color:var(--a)}
nav .add{flex:none;margin-left:auto;min-width:44px;min-height:44px;padding:0 12px;border-radius:22px;background:var(--a);color:#0A1020;font:700 15px Outfit,sans-serif;display:flex;align-items:center;justify-content:center;gap:6px}
nav .add .plus{font-size:26px;line-height:1}nav .add .txt{display:none}
@media(min-width:900px){#app{max-width:1120px}nav{margin:0}nav .brand{display:block;font-size:22px;font-weight:700;margin-right:18px}nav .tabs button{font-size:15px;padding:0 14px}nav .add{padding:0 20px}nav .add .plus{font-size:22px}nav .add .txt{display:inline}main.v-plata{max-width:720px;margin:0 auto;width:100%}}`;document.head.appendChild(st2);
const TIPOS={efectivo:'Efectivo',banco:'Banco',ahorro:'Ahorro',credito:'Crédito'};
cargar=async function(){const q=t=>SB.from(t).select();const[a,s,m,w,f,fj,ap,cu,tr]=await Promise.all([q('ajustes').maybeSingle(),q('sobres').eq('activo',true).order('orden'),q('movimientos').order('fecha',{ascending:false}).order('creado',{ascending:false}),q('semanas'),q('frecuentes'),q('fijos').eq('activo',true).order('dia'),q('aportes_fijos'),q('cuentas').eq('activa',true).order('orden'),q('traspasos')]);
 S.aj=a.data;S.sobres=s.data||[];S.movs=m.data||[];S.sems=w.data||[];S.frec=f.data||[];S.fijos=fj.data||[];S.aportes=ap.data||[];S.cuentas=cu.data||[];S.tras=tr.data||[];draw()};
/* ---- cálculos ---- */
function saldoC(c){const g=S.movs.filter(x=>x.cuenta_id==c.id).reduce((a,x)=>a+x.monto,0),i=S.sems.filter(x=>x.cuenta_id==c.id).reduce((a,x)=>a+(x.pago||0),0),e=S.tras.filter(x=>x.hacia==c.id).reduce((a,x)=>a+x.monto,0),s=S.tras.filter(x=>x.desde==c.id).reduce((a,x)=>a+x.monto,0);
 return c.tipo=='credito'?c.saldo_inicial+g-e+s:c.saldo_inicial+i-g+e-s}
function reunidoCred(c){const A=S.aportes.filter(a=>a.cuenta_id==c.id),f0=A.reduce((m,a)=>a.fecha<m?a.fecha:m,'9999-12-31');return Math.max(0,A.reduce((a,x)=>a+x.monto,0)-S.tras.filter(t=>t.hacia==c.id&&t.fecha>=f0).reduce((a,t)=>a+t.monto,0))}
function plata(){const C=S.cuentas||[],sum=t=>C.filter(c=>t.includes(c.tipo)).reduce((a,c)=>a+saldoC(c),0),gastar=sum(['efectivo','banco']),ahorro=sum(['ahorro']),deuda=sum(['credito']),apart=S.fijos.reduce((a,f)=>a+reunido(f),0)+C.filter(c=>c.tipo=='credito').reduce((a,c)=>a+reunidoCred(c),0);return{gastar,ahorro,deuda,apart,libre:gastar-apart}}
function semAhorro(){const h=lunesDe(hoyS());let t=0;for(let i=1;i<=4;i++){const l=addD(h,-7*i),f=addD(l,6);t+=S.movs.filter(x=>x.fecha>=l&&x.fecha<=f).reduce((a,x)=>a+x.monto,0)}return t>0?plata().ahorro/(t/4):null}
function cuentaDef(){const v=localStorage.getItem('cu_'+S.user.id);return S.cuentas.find(c=>c.id==v&&c.tipo!='ahorro')?v:(S.cuentas.find(c=>c.tipo=='banco')||S.cuentas.find(c=>c.tipo!='ahorro'))?.id}
const recuerda=id=>localStorage.setItem('cu_'+S.user.id,id);
const chipsC=(sel,fn,sa)=>S.cuentas.filter(c=>!(sa&&c.tipo=='ahorro')).map(c=>`<button class="chip ${c.id==sel?'on':''}" data-c="${c.id}" onclick="${fn}('${c.id}')">${esc(c.nombre)}</button>`).join('');
const marca=(box,id)=>document.querySelectorAll(box+' .chip').forEach(x=>x.classList.toggle('on',x.dataset.c==id));
/* ---- pantallas ---- */
draw=function(){const a=$('#app');if(!S.user)return vAuth();if(locked)return vPin();if(!S.aj?.listo)return vWizard();
 const v={inicio:vInicio,fijos:vFijos,cal:vCal,movs:vMovs,aj:vAjustes,plata:vPlata}[S.v](),T=[['inicio','Inicio'],['fijos','Fijos'],['cal','Calendario'],['movs','Gastos'],['aj','Ajustes']];
 a.innerHTML=`<nav><span class="brand">Gastos</span><div class="tabs">${T.map(t=>`<button class="${S.v==t[0]||(t[0]=='inicio'&&S.v=='plata')?'on':''}" onclick="ir('${t[0]}')">${t[1]}</button>`).join('')}</div><button class="add" aria-label="Anotar gastos" onclick="abrirGasto()"><span class="plus">+</span><span class="txt">Anotar gastos</span></button></nav><main class="v-${S.v}">${v}<button class="help" aria-label="Ayuda" onclick="ayuda()">?</button></main>`};
const _v2=vInicio;vInicio=function(){let h=_v2();const C=S.cuentas||[],p=plata();
 const card=C.length?`<button class="card" style="grid-column:1/-1;text-align:left;border:0;color:inherit;font:inherit;cursor:pointer" onclick="ir('plata')"><span class="m">Mi plata · toca para ver tus cuentas</span><div class="l"><span>Libre de verdad</span><b class="big3">${fm(p.libre)}</b></div><small>Para gastar ${fm(p.gastar)} · Ahorro ${fm(p.ahorro)}${p.deuda?` · Debes ${fm(p.deuda)}`:''}</small></button>`:`<button class="warn" style="grid-column:1/-1;text-align:left;border:0;font:inherit;cursor:pointer" onclick="ir('plata')">Aún no anotas dónde tienes tu plata. Toca aquí para crear tus cuentas.</button>`;
 return h.replace('</h1></div>','</h1></div>'+card)};
function vPlata(){const C=S.cuentas;if(!C.length)return `<h1>Mi plata</h1><p>Aquí anotas dónde tienes tu plata: efectivo, bancos, ahorro y crédito. Así la app sabe de dónde sale cada gasto y cuánto tienes de verdad.</p><button class="btn" onclick="semilla()">Crear mis cuentas</button><button class="btn2" onclick="nuevaCuenta()">Crear una cuenta a mano</button>`;
 const p=plata(),sa=semAhorro(),N=id=>esc(S.cuentas.find(c=>c.id==id)?.nombre||'Cuenta quitada');
 return `<h1>Mi plata</h1><div class="hero"><span>Plata libre de verdad</span><b>${fm(p.libre)}</b><span>Para gastar ${fm(p.gastar)} − apartado para fijos y crédito ${fm(p.apart)}</span></div>
 ${C.map(c=>{const s=saldoC(c);return `<div class="card"><div class="l"><b>${esc(c.nombre)}</b><small>${TIPOS[c.tipo]}</small></div><b class="big3">${fm(s)}</b>${c.tipo=='credito'?`<small>Debes ${fm(s)}${c.cupo?` · cupo disponible ${fm(c.cupo-s)} de ${fm(c.cupo)}`:''}</small>`:''}<div class="r2"><button class="btn2" onclick="corrige('${c.id}')">Corregir saldo</button><button class="btn2" onclick="nuevaCuenta('${c.id}')">Editar</button></div></div>`}).join('')}
 ${p.ahorro>0&&sa?`<div class="card"><small>Tu ahorro (${fm(p.ahorro)}) cubre ${sa.toFixed(1)} semanas de gasto, según tu promedio de las últimas 4 semanas.</small></div>`:''}
 <div class="r2"><button class="btn" onclick="traspaso()">Traspaso</button><button class="btn2" onclick="nuevaCuenta()">+ Cuenta</button></div>
 ${S.tras.length?'<h4>Últimos traspasos</h4>'+S.tras.slice().sort((a,b)=>b.fecha.localeCompare(a.fecha)).slice(0,8).map(t=>`<div class="mv"><div><b>${N(t.desde)} → ${N(t.hacia)}</b><small>${dm(t.fecha)}${t.nota?' · '+esc(t.nota):''}</small></div><b>${fm(t.monto)}</b><button class="x" aria-label="Borrar traspaso" onclick="delTras('${t.id}')">✕</button></div>`).join(''):''}`}
/* ---- cuentas y traspasos ---- */
async function semilla(){const L=[['Efectivo','efectivo'],['Santander (recibo pagos)','banco'],['Falabella (débito)','banco'],['MACH (ahorro)','ahorro'],['Tenpo (crédito)','credito']];
 const{error}=await SB.from('cuentas').insert(L.map((x,i)=>({nombre:x[0],tipo:x[1],orden:i,cupo:x[1]=='credito'?50000:null})));if(error)return toast(error.message);await cargar();toast('Listo. Ahora toca Corregir saldo en cada cuenta y anota lo que tienes hoy')}
function nuevaCuenta(id){const c=S.cuentas.find(x=>x.id==id)||{nombre:'',tipo:'banco',cupo:''},d=$('#dlg');
 d.innerHTML=`<h3>${id?'Editar':'Nueva'} cuenta</h3><input id="cn" placeholder="Nombre (ej. Falabella)" value="${esc(c.nombre)}" aria-label="Nombre"><select id="ct" aria-label="Tipo">${Object.keys(TIPOS).map(k=>`<option value="${k}" ${c.tipo==k?'selected':''}>${TIPOS[k]}</option>`).join('')}</select><input id="cc" inputmode="numeric" placeholder="Cupo (solo crédito)" value="${c.cupo||''}" aria-label="Cupo"><div class="r2">${id?`<button class="btn2" onclick="quitaCuenta('${id}')">Quitar</button>`:''}<button class="btn2" onclick="this.closest('dialog').close()">Cancelar</button><button class="btn" onclick="guardaCuenta('${id||''}')">Guardar</button></div>`;d.onclose=null;d.showModal()}
async function guardaCuenta(id){const o={nombre:$('#cn').value.trim(),tipo:$('#ct').value,cupo:parseM($('#cc').value)||null};if(!o.nombre)return toast('Falta el nombre');
 const r=id?await SB.from('cuentas').update(o).eq('id',id):await SB.from('cuentas').insert({...o,orden:S.cuentas.length});if(r.error)return toast(r.error.message);$('#dlg').close();cargar()}
async function quitaCuenta(id){if(confirm('¿Quitar esta cuenta? Los movimientos ya anotados se mantienen, pero dejan de sumarse a un saldo.')){await SB.from('cuentas').update({activa:false}).eq('id',id);$('#dlg').close();cargar()}}
async function corrige(id){const c=S.cuentas.find(x=>x.id==id),v=await ask(c.tipo=='credito'?`¿Cuánto debes hoy en ${c.nombre}?`:`¿Cuánto tienes hoy en ${c.nombre}?`,'','numeric');if(v==null)return;
 await SB.from('cuentas').update({saldo_inicial:c.saldo_inicial+parseM(v)-saldoC(c)}).eq('id',id);cargar()}
function traspaso(){if(S.cuentas.length<2)return toast('Necesitas al menos dos cuentas');const o=S.cuentas.map(c=>`<option value="${c.id}">${esc(c.nombre)}</option>`).join(''),d=$('#dlg');
 d.innerHTML=`<h3>Traspaso entre cuentas</h3><small class="m">Sirve para depositar efectivo, sacar del cajero, pasar plata entre bancos, pagar el crédito o ahorrar. No cuenta como gasto.</small><small>Desde</small><select id="td">${o}</select><small>Hacia</small><select id="th">${o}</select><input id="tm" inputmode="numeric" placeholder="Monto" aria-label="Monto"><input id="tn" placeholder="Nota (opcional)" aria-label="Nota"><div class="r2"><button class="btn2" onclick="this.closest('dialog').close()">Cancelar</button><button class="btn" onclick="guardaTras()">Guardar</button></div>`;$('#th').selectedIndex=1;d.onclose=null;d.showModal()}
async function guardaTras(){const o={desde:$('#td').value,hacia:$('#th').value,monto:parseM($('#tm').value),nota:$('#tn').value.trim()||null};if(o.desde==o.hacia||!o.monto)return toast('Elige dos cuentas distintas y un monto');const{error}=await SB.from('traspasos').insert(o);if(error)return toast(error.message);$('#dlg').close();cargar()}
async function delTras(id){await SB.from('traspasos').delete().eq('id',id);cargar()}
/* ---- de qué cuenta sale o entra cada movimiento ---- */
const _ag=abrirGasto;abrirGasto=function(){_ag();const d=$('#sheet');if(!d.open||!S.cuentas.length)return;S.cp=cuentaDef();$('#gf').insertAdjacentHTML('beforebegin',`<small class="m">Pagué con</small><div id="gc" class="chips">${chipsC(S.cp,'selCuenta',1)}</div><small>Si pagaste con tu ahorro, elige otra cuenta y escríbelo en la nota; luego haz el traspaso desde el ahorro.</small>`)};
const selCuenta=id=>{S.cp=id;marca('#gc',id)};
guardaG=async function(){const monto=parseM($('#gm').value),nota=$('#gn').value.trim();if(!monto||!S.gs)return toast('Falta el monto o el sobre');
 const o={monto,nota:nota||null,sobre_id:S.gs,fecha:$('#gf').value||hoyS()};if(S.cuentas.length&&S.cp){o.cuenta_id=S.cp;recuerda(S.cp)}
 const{error}=await SB.from('movimientos').insert(o);if(error)return toast(error.message);
 if($('#gq').checked)await SB.from('frecuentes').insert({nombre:nota||S.sobres.find(b=>b.id==S.gs).nombre,sobre_id:S.gs,monto:$('#gx').checked?monto:null});
 $('#sheet').close();toast('Gasto guardado');cargar()};
undoNow=async function(){if(!undo)return;const{id,monto,fecha,sobre_id,nota,cuenta_id,extra}=undo;undo=null;$('#toast').classList.remove('show');await SB.from('movimientos').insert({id,monto,fecha,sobre_id,nota,cuenta_id,extra});cargar()};
regPago=function(){const l=lunesDe(hoyS()),s=S.sems.find(x=>x.lunes==l),d=$('#dlg');S.cr=s?.pago!=null?(s.cuenta_id||'none'):(cuentaDef()||'none');
 d.innerHTML=`<h3>¿Cuánto te pagaron esta semana?</h3><input id="pm" inputmode="numeric" value="${s?.pago??S.aj.pago_tipico??''}" aria-label="Monto del pago">${S.cuentas.length?`<small class="m">¿A qué cuenta llegó?</small><div id="pc" class="chips">${chipsC(S.cr,'selPago')}<button class="chip ${S.cr=='none'?'on':''}" data-c="none" onclick="selPago('none')">Ya estaba en mi saldo</button></div>`:''}<div class="r2"><button class="btn2" onclick="this.closest('dialog').close()">Cancelar</button><button class="btn" onclick="guardaPago()">Guardar</button></div>`;d.onclose=null;d.showModal()};
const selPago=id=>{S.cr=id;marca('#pc',id)};
async function guardaPago(){const o={user_id:S.user.id,lunes:lunesDe(hoyS()),pago:parseM($('#pm').value)};if(S.cuentas.length){o.cuenta_id=S.cr=='none'?null:S.cr;if(o.cuenta_id)recuerda(o.cuenta_id)}
 const{error}=await SB.from('semanas').upsert(o,{onConflict:'user_id,lunes'});if(error)return toast(error.message);$('#dlg').close();cargar()}
confFijo=function(id){const f=S.fijos.find(x=>x.id==id),u=S.movs.find(x=>x.extra?.fijo_id==id&&x.cuenta_id),d=$('#dlg');S.cf=u?.cuenta_id||cuentaDef();S.fid=id;
 d.innerHTML=`<h3>Pagar ${esc(f.nombre)}</h3><p>${fm(f.monto)}${S.cuentas.length?' · ¿Desde qué cuenta?':''}</p><div id="fc" class="chips">${chipsC(S.cf,'selFC',1)}</div><div class="r2"><button class="btn2" onclick="this.closest('dialog').close()">Cancelar</button><button class="btn" onclick="pagaFijo()">Confirmar pago</button></div>`;d.onclose=null;d.showModal()};
const selFC=id=>{S.cf=id;marca('#fc',id)};
async function pagaFijo(){const f=S.fijos.find(x=>x.id==S.fid),o={monto:f.monto,nota:f.nombre,fecha:hoyS(),sobre_id:null,extra:{fijo_id:f.id}};if(S.cuentas.length&&S.cf){o.cuenta_id=S.cf;recuerda(S.cf)}
 const{error}=await SB.from('movimientos').insert(o);if(error)return toast(error.message);$('#dlg').close();toast('Pago confirmado');cargar()}
const _ay=ayuda;ayuda=function(){if(S.v!='plata')return _ay();const d=$('#dlg');d.innerHTML=`<h3>Mi plata</h3><p>Aquí está tu plata de verdad, repartida por cuentas. "Corregir saldo" lo ajusta a lo que realmente tienes. "Traspaso" mueve plata entre tus cuentas sin contarla como gasto: sirve para depositar efectivo, sacar del cajero, pagar el crédito o ahorrar. La plata libre de verdad es lo que tienes para gastar, menos lo apartado para fijos y para pagar el crédito, que se cobra aparte, como un fijo.</p><button class="btn" onclick="this.closest('dialog').close()">Entendido</button>`;d.onclose=null;d.showModal()};
/* ---- cuenta habitual de cada fijo y suscripción ---- */
const _ef=editaFijo;editaFijo=function(id){_ef(id);if(!S.cuentas.length)return;const f=S.fijos.find(x=>x.id==id)||{},sel=id?f.cuenta_id:cuentaDef();
 $('#fs').closest('label').insertAdjacentHTML('afterend',`<small class="m">Se paga desde</small><select id="fcu" aria-label="Se paga desde"><option value="">Sin cuenta</option>${S.cuentas.map(c=>`<option value="${c.id}" ${sel==c.id?'selected':''}>${esc(c.nombre)}</option>`).join('')}</select>`)};
guardaFijo=async function(id){const dia=parseInt($('#fd').value),o={nombre:$('#fn').value.trim(),monto:parseM($('#fo').value),dia,suscripcion:$('#fs').checked};if($('#fcu'))o.cuenta_id=$('#fcu').value||null;if(!o.nombre||!o.monto||!(dia>=1&&dia<=31))return toast('Completa nombre, monto y un día entre 1 y 31');
 const r=id?await SB.from('fijos').update(o).eq('id',id):await SB.from('fijos').insert(o);if(r.error)return toast(r.error.message);$('#dlg').close();cargar()};
const _vf=vFijos;vFijos=function(){let h=_vf();S.fijos.forEach(f=>{const c=S.cuentas.find(x=>x.id==f.cuenta_id);if(c)h=h.replace(`<span>${fm(f.monto)} · día ${f.dia}</span>`,`<span>${fm(f.monto)} · día ${f.dia} · ${esc(c.nombre)}</span>`)});return h};
const _cf=confFijo;confFijo=function(id){const f=S.fijos.find(x=>x.id==id);_cf(id);if(f?.cuenta_id){S.cf=f.cuenta_id;marca('#fc',f.cuenta_id)}};
if(S.user)cargar();
